version: "3.3"

services:
  mongo:
    build: ./mongo
    image: mongo
    container_name: "mongo"
    env_file:
     - .env
    environment:
     - MONGO_DATA_DIR=/data/db
     - MONGO_LOG_DIR=/dev/null
    volumes:
     - $MONGO_DATA_FOLDER:/data/db
    ports:
     - "27017:27017"

  metrics-app:
    build:
      context: ./metrics-app
      args:
        SERVER_PORT: $SERVER_PORT
    image: metrics-app
    container_name: "metrics-app"
    env_file:
     - .env
    links:
     - mongo
    ports:
     - "$SERVER_PORT:$SERVER_PORT"
